### PR TITLE
Rotation code

### PR DESCRIPTION
**Pull request by Yardie-**
I have added my rotation code examples still need to be fixed though.

### CODE REVIEW

**Comment by Yardie-** [comment]
Please don't implement this pull I finally had a chance to test it and there is something wrong with the 4 bit per pixel translation.

I can't see how to delete the pull request from my end

**Comment by k-omura** [comment]
OK Then close it once.  
The problem of 4bit does not occur in the one implemented here only for rotation.
Thank you!

**Comment by k-omura** [comment]
I created a branch with only rotation added.
I haven't had any problems with this code.
I haven't implemented your ideas about text rotation and orientation yet. Rotation only version.
https://github.com/k-omura/truetype_Arduino/blob/add_rotation/src/truetype_Arduino.cpp

**Comment by Yardie-** [comment]
Good idea.
I'll implement it on my lilygo and see if it is jut my misunderstanding of what I see in the serial printed framebuffer it could simply be that

**Comment by Yardie-** [comment]
ultimately it was a unsigned signed issue

**Pull request closed without merging**
